name: CI/CD

on: push

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: QEMU        
        uses: docker/setup-qemu-action@v2
      
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Add GitHub NuGet Source
        run: |
          dotnet nuget add source --username $OWNER --password $GITHUB_TOKEN --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$OWNER/index.json"
          dotnet nuget list source
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          OWNER: ${{ secrets.PACKAGE_OWNER }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: mindaugasa/ecb_rates_update_service:latest 
