name: CI/CD

on: push

jobs:
  build:
    name: Building image
    runs-on: ubuntu-lates
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        platforms: linux/amd64,linux/arm64
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mindaugasa/ecb_rates_update_service_cicd:latest 